defaults:
#  - replay_buffer@_global_: dataloader
#  - domain_randomization@_global_: none
#  - obs@_global_: image_only
  - agent: td3
#  - jump_start@_global_: none
#  - goal_cond@_global_: none
#  - multitask@_global_: none
#  - task@_global_: nut_assembly_image
#  - override hydra/launcher: submitit_local


#env_name: 'Ant-v3'
#env_name: 'HalfCheetah-v2'
env_name: 'Pendulum-v1'
save_dir: './tmp/'
seed: 42
eval_episodes: 10
log_interval:  1000
eval_interval: 5000
batch_size: 256
updates_per_step: 1
max_steps: 1000000
replay_buffer_size: 1000000
start_training: 500
tqdm: True
save_video: False
track: False
wandb_project_name: "jrl"
wandb_entity: ""
grad_norm_clipping: 10.0
action_repeat: 1
pixels: False
num_envs: 1

envpool: False
#envpool: True

replay_buffer_type: "basic"
#replay_buffer_type: "compressed"
n_step: 1
replay_buffer_num_workers: 4
save_snapshot: False


# reset interval
# https://arxiv.org/pdf/2205.07802.pdf
reset: False
#reset: True
reset_interval: 200000
