#env_name: 'Ant-v3'
#env_name: 'HalfCheetah-v2'
env_name: 'Pendulum-v1'
save_dir: './tmp/'
seed: 42
eval_episodes: 10
log_interval:  1000
eval_interval: 5000
batch_size: 256
updates_per_step: 1
max_steps: 1000000
replay_buffer_size: 1000000
start_training: 5000
tqdm: True
save_video: False
track: False
wandb_project_name: "jrl"
wandb_entity: ""
grad_norm_clipping: 10.0


# TD3 params
policy_freq: 2
policy_noise: 0.2
noise_clip: 0.5
exploration_noise: 0.1

# reset interval
# https://arxiv.org/pdf/2205.07802.pdf
reset: False
reset_interval: 200000
