defaults:
  - config

agent_name: 'DrQ'

env_name: 'cheetah-run'
batch_size: 64
updates_per_step: 1
max_steps: 500000
replay_buffer_size: 100000
start_training: 100
pixels: True
action_repeat: null

gray_scale: False
image_size: 84

DrQ:
  # SAC
  policy_freq: 1
  target_entropy: None
  backup_entropy: 0.5
  init_temperature: 1.0
  init_mean: None
  policy_final_fc_init_scale: 1.0
  actor_lr:  0.0003
  critic_lr: 0.0003
  temperature_lr: 0.0003
  # Image
  hidden_dims: [256, 256]
  cnn_features: [32, 32, 32, 32]
  cnn_strides: [2, 1, 1, 1]
  cnn_padding: 'VALID'
  latent_dim: 50
